apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deploy-update-controller-{{ deployment }}
  namespace: {{ target_namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deploy-update-controller-{{ deployment }}
subjects:
- kind: ServiceAccount
  name: {{ serviceAccountName }}
  namespace: {{ ControllerNamespace }}
