version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/deployments/terraform"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/build"
    schedule:
      interval: "daily"
