apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ target_namespace }}
  name: deploy-update-controller-{{ deployment }}
rules:
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]