apiVersion: batch/v1
kind: CronJob
metadata:
  name: deploy-update-controller-{{ deployment }}
  namespace: {{ ControllerNamespace }}
spec:
  schedule: "15 4 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ serviceAccountName }}
          containers:
          - name: deploy-update-controller-{{ deployment }}
            image: {{ image }}
            imagePullPolicy: always
            serviceAccount: {{ serviceAccountName }}
            command:
            - ./deploy-update-controller
            env:
            - name: IN_CLUSTER
              value: "true"
          restartPolicy: OnFailure
